# Development override file
version: '3.8'

services:
  backend:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app:cached
      - /app/__pycache__
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    
  # Hot reload for development
  postgres:
    ports:
      - "5433:5432"  # Different port to avoid conflicts
      
  redis:
    ports:
      - "6380:6379"  # Different port to avoid conflicts